import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="w-full h-10 flex justify-end items-center gap-10 px-4 bg-black">
          <Link
            href="/"
            className="text-sm font-medium text-white hover:text-violet-600"
          >
            Home
          </Link>
          <Link
            href="/blog"
            className="text-sm font-medium text-white hover:text-violet-600"
          >
            Blog
          </Link>
          <Link
            href="/Contact"
            className="text-sm font-medium text-white hover:text-violet-600"
          >
            Contact
          </Link>
        </nav>
        {children}
        <footer className="w-full h-10 bg-black flex items-center justify-center">
          <span className="text-white text-sm font-medium">
            @2024 SRI GOKUL RANJITH
          </span>
        </footer>
      </body>
    </html>
  );
}
